version: '3'
services:
  django:
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/app
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 134425
      POSTGRES_DB: playlist
    volumes:
      - postgress_date:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django


volumes:
  postgress_date: