# Generated by Django 5.0.1 on 2024-02-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('brief', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_fa', models.CharField(blank=True, max_length=100)),
                ('lastname_fa', models.CharField(blank=True, max_length=100)),
                ('firstname_en', models.CharField(blank=True, max_length=100)),
                ('lastname_en', models.CharField(blank=True, max_length=100)),
                ('date_brith', models.DateField(blank=True, null=True)),
                ('stage_name_fa', models.CharField(max_length=100)),
                ('stage_name_en', models.CharField(max_length=100)),
                ('career_start_date', models.DateField()),
                ('bio_fa', models.TextField()),
                ('bio_en', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='song.country')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('file_path', models.FileField(upload_to='songs/')),
                ('lyrics_en', models.TextField(blank=True, null=True)),
                ('lyrics_fa', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(upload_to='songs/covers/')),
                ('album_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='album.album')),
                ('category_id', models.ManyToManyField(to='song.category')),
                ('genre_id', models.ManyToManyField(to='song.genre')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
